---
# Source: datahub/templates/datahub-encryption-secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-encryption-secrets"
type: Opaque
data: 
  # check, if a secret is already set
  # if not set, then generate a new password
  encryption_key_secret: WXNFVjV5ZHNsblZpM1VDNnprVVc=
